# -*- coding: utf-8 -*-
"""Untitled7.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1M0Px1f0NLSUwYqu44YF4qBABlGK-1sVu
"""

import pandas as pd
import matplotlib.pyplot as plt

a=pd.read_csv('/content/carscsv.csv')
a



#line chart of kilometer and price
x=a['Kilometer']
y=a['Price']
plt.plot(x,y,marker='o')
plt.title('kilometer and price analysis')
plt.xlabel('Kilometer')
plt.ylabel('Price')
plt.show()

#company and fuel tank capacity - Bar plot
categories=a['Make']
values=a['Fuel Tank Capacity']
plt.bar(categories,values)
plt.title('company and fuel analysis')
plt.xlabel('fuel tank capacity')
plt.ylabel('Company')

#histogram
c=a['Price']
plt.hist(c,bins=20,edgecolor='k')
plt.title('Frequency of Car price')
plt.ylabel('Frequency')
plt.xlabel('Value')
plt.show()

#year and kilometer scatter plot
d=a['Year']
e=a['Kilometer']
plt.scatter(d,e)
plt.title('kilometer analysis')
plt.xlabel('year')
plt.ylabel('kilometer')
plt.show()

f=a.head(10)
categories=f['Make']
values=f['Year']
plt.pie(values,labels=categories,autopct='%1.1f%%')
plt.title("pie")
plt.show()

g=a['Price']
plt.hist(g,density=True,bins=30,alpha=0.5)
plt.xlabel('values')
plt.ylabel('Density')
plt.show()

#line chart of year and price
x=a['Year']
y=a['Price']
plt.plot(x,y,marker='o')
plt.title('year and price analysis')
plt.xlabel('year')
plt.ylabel('Price')
plt.show()

#company and fuel Kilometer - Bar plot
categories=a['Make']
values=a['Kilometer']
plt.bar(categories,values)
plt.title('company and Kilometer analysis')
plt.xlabel('Kilometer')
plt.ylabel('Company')

#histogram
c=a['Kilometer']
plt.hist(c,bins=20,edgecolor='k')
plt.title('Frequency of Kilometer')
plt.ylabel('Frequency')
plt.xlabel('Value')
plt.show()

#Price and kilometer scatter plot
d=a['Price']
e=a['Kilometer']
plt.scatter(d,e)
plt.title('kilometer analysis')
plt.xlabel('Price')
plt.ylabel('kilometer')
plt.show()

categories=f['Make']
values=f['Price']
plt.pie(values,labels=categories,autopct='%1.1f%%')
plt.title("pie")
plt.show()

h=a['Kilometer']
plt.hist(h,density=True,bins=30,alpha=0.5)
plt.xlabel('values')
plt.ylabel('Density')
plt.show()