# -*- coding: utf-8 -*-
"""Assingment 2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1henzcSODNTcx4vx9yKUYOBrJFDc_U_67
"""

Product_details=[]
Supplier_details={}
Customer_details=[]
gender={}
fp1=open("Sales.csv","r")
data=fp1.readline( )
while(True):
  data=fp1.readline()
  if not data:
    break;
  print (data)
  data=data.replace("\n","")
  temp=data.split(",")
  print (temp)
  Product_details.append(temp[1])
  Customer_details.append(temp[3])
  Supplier_details.update({temp[0]:temp[2]})
  gender.update({temp[3]: temp [4]})

fp1.close( )
Customers_details=tuple(Customer_details)
print(type(Customer_details))

frequency = {}
for item in Product_details:
  if item in frequency:
     frequency[item] += 1
  else:
     frequency[item] = 1
print(frequency)
marklist = sorted(frequency.items(),key = lambda x:x[1], reverse = True)
sortdict = dict(marklist)
print(sortdict)
print("The most popular product for sales",list(sortdict.keys())[0],"sold",list(sortdict.values())[0],"times")

frequency = {}
for item in Supplier_details.values():
   if item in frequency:
       frequency[item] += 1
   else:
      frequency[item] = 1
print(frequency)
marklist = sorted(frequency.items(),key = lambda x:x[1], reverse = True)
sortdict = dict(marklist)
print(sortdict)
print("Best Supplier",list(sortdict.keys())[0],"sold",list(sortdict.values())[0],"Items")

frequency = {}
for item in Customer_details:
   if item in frequency:
      frequency[item] += 1
   else:
      frequency[item] = 1
marklist = sorted(frequency.items(),key = lambda x:x[1], reverse = True)
print("Most Product Buyer",list(sortdict.keys())[0],"buy",list(sortdict.values())[0],"Items")

"""Female Gender Counter

"""

from collections import Counter
countGender = Counter(gender)
a = (countGender.get("Female"))
print(f'No of Females are:(6)')