# -*- coding: utf-8 -*-
"""ASSignment-3_526.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/14esQbaTF2iG0s4BpOI-_oqdgOQfrss1y
"""

import numpy as np
a1=np.array([[1,2,3],[4,5,6],[7,8,9]])
a2=np.array([[9,8,7],[6,5,4],[3,2,1]])
result=np.array(a1+a2)
print("using operator",result)
result=np.add(a1,a2)
print("using numpy function\n",result)
print(a1.shape)
print(a1.ndim)





result=np.subtract(a1,a2)
print('using numpy function')
print(result)
print("using operator")
c=a1-a2
print(c)

result=np.multiply(a1,a2)
print("using numpy function")
print(result)
print("using operator")
v=a1*a2
print(v)

result=np.divide(a1,a2)
print("using numpy function")
print(result)
print("using operator")
v=a1/a2
print(v)

result=np.mod(a1,a2)
print("using numpy function")
print(result)
print("using operator")
v=a1%a2
print(v)

result=np.transpose(a1)
print(result)

result=np.hstack(a1)
print(result)

p=np.arange(0,22,3).reshape(2,4)
print(p)

p=np.empty_like(a1)
print(p)

l=np.array([1,2,3,4,5,6])

a3=np.loadtxt("/content/testmarks1.csv",delimiter=',',dtype=str,skiprows=1)
print(a3)
sal=[]
exp=[]
for i in a3:
  sal.append(float(i[2]))
  exp.append(float(i[3]))
print('This is salary',sal)
print('This is expenditure',exp)

"""CONVERTING LIST TO ARRAY AND MAX OF AN ARRAY

"""

arr_sal=np.array(sal)
arr_exp=np.array(exp)
m=max(arr_sal)
print('The max in sal is',m)

"""DATA STACKING"""

c=np.stack((arr_sal,arr_exp),axis=0)
print('The Stacked Array is\n',c)

""" SEARCHING"""

v=np.where(arr_exp==27.27)
print(v)

"""SORTING"""

B=np.sort(arr_sal)
print('This sorted array',B)

"""FILTER

"""

filter_arr=[]
for element in arr_sal:

  if element > 26:
    filter_arr.append(True)
  else:
    filter_arr.append(False)

newarr=arr_sal[filter_arr]

print('Every number above 26',newarr)

"""SUMATION

"""

n=sum(arr_sal)
print('The sum of all the values of SAL is',n)

"""SLICING

"""

f=arr_exp[0:5]
print("The first 5 elemnts of SAL is",f)

"""ADDITION OF TWO ARRAY"""

ADD=arr_sal+arr_exp
print('The addition of two arrays is',ADD)

"""COPYING OF ARRAY

"""

k=np.copy(arr_sal)
print(k)

"""AVERAGE"""

j=np.average(arr_exp)
print('The average expenditure is',j)