# -*- coding: utf-8 -*-
"""assign04.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1J-DuoFet-qfsji4Bjfrx1bnmB3sGasHC
"""

import pandas as pd
df=pd.read_csv('/content/car csv.csv')
df

#print name of all car models
print(df['Model'])

#print model wise price
print(df[['Model','Price']])

#print model wise engine power
print(df[['Model','Engine']])

#describe about data
print(df.describe())

#print highest priced car
print(df['Price'].max())

#lowest priced car
print(df['Price'].min())

#average price of car
print(df['Price'].mean())

#median of car price in data
print(df['Price'].median())

#highest fuel tank capacity in car
print(df['Fuel Tank Capacity'].max())

#number of data
print(df.count())

#model wise count of car
print(df['Model'].value_counts())

#cars having cost greater than 2500000
print(df.loc[df['Price']>2500000])

#cars having price less than 1000000
print(df.loc[df['Price']<1000000])

#print first 10 data
print(df.head(10))

#print last 10 data
print(df.tail(10))

#car from year 2017
print(df.groupby('Year').get_group(2017))

#number of blank data spaces
df.isna().sum()

#types used in data
df.dtypes



#location wise information about price
a=df.groupby('Location').agg({'Price':['sum','min','max','count']})
a

#graph
import matplotlib.pyplot as plt
x=df['Fuel Tank Capacity']
y=df['Kilometer']
plt.plot(x,y,marker=0)